config/routes.rb
Mrlowe::Application.routes.draw do
  resources :appointments
  root 'appointments#new'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible :date, :hour
  validates :date,  :presence => true
  validates :hour,  :presence => true,
                    :uniqueness => {:scope => :date}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def index
    date_from_ajax_jquery_picker = params[:matched_date]
    find_date = Appointment.where(:date => date_from_ajax_jquery_picker)
    appointment_hours = find_date.collect {|x| x.hour}
    render :json => appointment_hours
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def new
    @appointment = Appointment.new
  end

  def create
     @appointment = Appointment.new(params[:appointment])
      if @appointment.save

        redirect_to root_path, notice: "An email was sent with your appointment details"
      else
        redirect_to root_path, notice: "Please try again"
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.haml
#form_holder
  .row
    .small-3.columns

      #datepicker
      #final_date
        %h2
      #final_hour
        %h2
    .small-4.columns

      #appointment_details
        #availability
          %h6
        #hour_picker
          %table.hours{:border => "1"}
            %tr.cal_table
              %td.0700
                7:00 am
            %tr.cal_table2
              %td.0800
                8:00 am
            %tr.cal_table
              %td.0900
                9:00 am
            %tr.cal_table2
              %td.1000
                10:00 am
            %tr#5.cal_table
              %td.1100
                11:00 am
            %tr#6.cal_table2
              %td.1200
                12:00 pm
            %tr#7.cal_table
              %td.1300
                1:00 pm
            %tr#8.cal_table2
              %td.1400
                2:00 pm
            %tr#8.cal_table2
              %td.1500
                3:00 pm
            %tr#8.cal_table2
              %td.1600
                4:00 pm

  = simple_form_for @appointment do |f|
    = f.hidden_field :hour
    = f.hidden_field :date
    = f.submit

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th>Hour</th>
      <th>Date</th>
      <th>Active</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.hour %></td>
        <td><%= appointment.date %></td>
        <td><%= appointment.active %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.haml
#hero
  #hero_text
    %h1 Mr Lowes!
    %h2 Tour Bus Transportation
    %h2.ja Montego Bay, Jamaica
    %a.button{"data-reveal-id" => "myModal", :href => "#"}
      Book
#page_wrap
  #main

    #content
      %h1
        %span.icon-bus
        Fast. Honest. Reliable.
      %p
        %strong
          Hello!
          %em Wah Gwan!
      %p
        I want to be the first to give you a warm welcome you to Jamaica!
        This country is very dear to me. I love showing visitors its natural
        beauty and authentic Jamaican hospitality.&nbsp;I can offer
        %strong specialized packages
        to ensure you have the
        = succeed "," do
          %strong most memorable experience possible
        be it a quick jaunt to the Montego Bay craft market, winding up the
        jungle-lined roads into the hills, taking you to the very best spot to
        for fresh pineapple and mangoes, or an adventure of your choosing.
      %p
        I am a
        = succeed "," do
          %strong safe
        = succeed "," do
          %strong prompt
        and
        %strong licensed
        tour driver. My sightseeing tour bus, “Be Happy,”
        %strong seats up to twenty-six
        and is equipped with an
        %strong excellent air conditioner
        for your comfort.
      %p
        I have recently received high
        %strong accolades
        from my peers for my
        = succeed "," do
          %strong punctuality
        driving
        = succeed "," do
          %strong ability
        = succeed "," do
          %strong cleanliness
        and
        = succeed "." do
          %strong attentiveness
      %p Please contact me as soon as possible as I tend to book up fast.
      %p Best,
      %p Mr. Stubbs
      #prices
        %h3
          %span.icon-tag
          Popular Destinations
        %ul
          %li Ocho Rios
          %li Negril
          %li Dunn's River Falls
          %li Dolphin Cove
          %li Downtown Montego
          %li Rose Hall Great House
      .call_button
        %p
          %em
            Call today!
            %a{:href => "tel:+18769959466"} +1-876-995-9466
#copyright
  © Mr. Stubbs
  %span.copyright_year 2013

#myModal.reveal-modal{:class => "xlarge"}
  %h2 Appointment
  = render "form"
  %a.close-reveal-modal ×

app/views/layouts/application.haml
!!!
%html
  %head
    %title Mrlowes
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/custom.modernizr"

    = csrf_meta_tags

  %body
    = yield

    = javascript_include_tag "application"